name: Build and push a development version on docker 

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        type: string
        description: Docker image tag
        required: true
        default: "latest-develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build -x test

  docker-build:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Create more disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/google/chrome 
          sudo rm -rf /opt/microsoft/msedge 
          sudo rm -rf /opt/microsoft/powershell 
          sudo rm -rf /opt/pipx 
          sudo rm -rf /usr/lib/mono 
          sudo rm -rf /usr/local/julia* 
          sudo rm -rf /usr/local/lib/android 
          sudo rm -rf /usr/local/lib/node_modules 
          sudo rm -rf /usr/local/share/chromium 
          sudo rm -rf /usr/local/share/powershell 
          sudo rm -rf /usr/share/dotnet 
          sudo rm -rf /usr/share/swift
      - uses: actions/checkout@v4
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          dockerfile: Dockerfile.software
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: lfoppiano/software-mentions
          registry: docker.io
          pushImage: true
          tags:  |
            latest-develop, ${{ github.event.inputs.custom_tag}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
